add map generation from file
bashenjoyers/superrogue pull request #22
Opened 2022-11-19 22:25 UTC by mandelshtamd

2022-11-19 23:30 UTC, bagrorg requested changes

2022-11-19 23:30 UTC, bagrorg commented on src/Common/environmentVariables/EnvironmentVariablesProvider.h
> +    class EnvironmentVariablesProvider {
Класс ради класса
Сделай лучше оберту над `getenv`

2022-11-19 23:30 UTC, bagrorg commented on src/Model/GameModel/Map/Generator/FileGenerating/MapEntityProvider.h
> +    std::map<int, GameModel::Abstract::MapEntity> entityMapping;
Здесь видимо ключи в char

2022-11-19 23:30 UTC, bagrorg commented on src/Model/GameModel/Map/Generator/FileGenerating/FileReader.cpp
> +    if (file.is_open()) {
Лучше уведомить об ошибке

2022-11-19 23:30 UTC, bagrorg commented on src/Model/GameModel/Map/Generator/FileGenerating/FileReader.cpp
> +        file.close();
На будущее это не обязательно -- RAII все сделает за тебя

2022-11-19 23:30 UTC, bagrorg commented on src/Model/GameModel/Map/Generator/FileGenerating/MapEntityProvider.h
> +class MapEntityProvider {
Выглядит как просто обертка над `std::map`
Пусть будет но вообще хз зачем это

2022-11-19 23:30 UTC, bagrorg commented on src/Model/GameModel/Map/Generator/FileGenerating/FileGenerator.h
> +        std::shared_ptr<MapEntityProvider> mapEntityProvider;
Нет причины делать здесь shared_ptr -- лишний random acess
Этот ресурс не разделяется

2022-11-19 23:30 UTC, bagrorg commented on src/Model/GameModel/Map/Generator/FileGenerating/FileGenerator.h
> +        std::shared_ptr<FileReader> fileReader;
Same

2022-11-19 23:30 UTC, bagrorg commented on src/Model/GameModel/Map/Generator/FileGenerating/FileGenerator.h
> +        std::shared_ptr<Common::EnvironmentVariablesProvider> environmentVariablesProvider;
Same

2022-11-19 23:30 UTC, bagrorg commented on src/Model/GameModel/Map/Generator/FileGenerating/FileGenerator.cpp
> +    std::string pathToMap = environmentVariablesProvider->getEnvironmentVariable(mapEnvVariableKey);
Ты тут достал путь до директории с картой но не добавил имя файла карты

2022-11-19 23:30 UTC, bagrorg commented on src/Model/GameModel/Map/Generator/FileGenerating/FileGenerator.cpp
> +    std::vector<std::string> fileContent = fileReader->readFile(pathToMap);
Вообще std::vector<std::string> лучше везде заменить на std:;vector<std::vector<char>>, чтобы лучше понимать что это карта, а не массив неких строк

2022-11-19 23:30 UTC, bagrorg commented on src/Model/GameModel/Map/Generator/FileGenerating/FileGenerator.cpp
> +    std::vector<std::vector<Abstract::MapEntity>> result = std::vector<std::vector<Abstract::MapEntity>>();
= ... тож не обязательно, бай дефолт всегда зовется дефолтный конструктор типа

2022-11-19 23:33 UTC, mandelshtamd commented on src/Common/environmentVariables/EnvironmentVariablesProvider.h
> +    class EnvironmentVariablesProvider {
Не согласен. Другой функциональности по работе с переменными окружения у нас в бизнес-логике не предвидится, при этом  очевидно эту функциональность лучше выносить в отдельную сущность, чтобы код не дублировался. Это не класс ради класса

2022-11-19 23:35 UTC, mandelshtamd commented on src/Model/GameModel/Map/Generator/FileGenerating/FileGenerator.cpp
> +    std::vector<std::string> fileContent = fileReader->readFile(pathToMap);
на этом этапе это именно массив строк из файла, суть функции как раз карту из нее и сделать

2022-11-19 23:37 UTC, mandelshtamd commented on src/Model/GameModel/Map/Generator/FileGenerating/FileGenerator.cpp
> +    std::string pathToMap = environmentVariablesProvider->getEnvironmentVariable(mapEnvVariableKey);
мы вроде договорились, что в системную переменную кладем путь до файла

2022-11-19 23:37 UTC, mandelshtamd commented on src/Model/GameModel/Map/Generator/FileGenerating/FileReader.cpp
> +        file.close();
ок

2022-11-19 23:38 UTC, mandelshtamd commented on src/Common/environmentVariables/EnvironmentVariablesProvider.h
> +namespace GameModel::Map {
а какой нужно?

2022-11-19 23:38 UTC, mandelshtamd commented on src/Common/environmentVariables/EnvironmentVariablesProvider.h
> +namespace GameModel::Map {
а, понял

2022-11-19 23:38 UTC, mandelshtamd commented on src/Common/environmentVariables/EnvironmentVariablesProvider.h
> +namespace GameModel::Map {
ты просто не актуальную версию файла комментил, уже пофиксил

2022-11-19 23:39 UTC, mandelshtamd commented on src/Model/GameModel/Map/Generator/FileGenerating/MapEntityProvider.h
> +    std::map<int, GameModel::Abstract::MapEntity> entityMapping;
исправил

2022-11-19 23:39 UTC, mandelshtamd commented on src/Model/GameModel/Map/Generator/FileGenerating/FileGenerator.h
> +        std::shared_ptr<MapEntityProvider> mapEntityProvider;
То говоришь писать везде shared_ptr, то оказывается нигде не нужен...

2022-11-19 23:40 UTC, mandelshtamd commented on src/Model/GameModel/Map/Generator/FileGenerating/FileGenerator.h
> +        std::shared_ptr<Common::EnvironmentVariablesProvider> environmentVariablesProvider;
fixed

2022-11-19 23:40 UTC, mandelshtamd commented on src/Model/GameModel/Map/Generator/FileGenerating/FileGenerator.h
> +        std::shared_ptr<FileReader> fileReader;
fixed

2022-11-19 23:41 UTC, mandelshtamd commented on src/Model/GameModel/Map/Generator/FileGenerating/FileReader.cpp
> +    if (file.is_open()) {
как это лучше сделать? эксепшн кинуть?

2022-11-21 16:02 UTC, bagrorg commented on src/Model/GameModel/Map/Generator/FileGenerating/FileGenerator.cpp
> +    std::string pathToMap = environmentVariablesProvider->getEnvironmentVariable(mapEnvVariableKey);
Нет, в переменной окружения должен быть путь до контента, не до конкретной карты

2022-11-21 18:48 UTC, mandelshtamd commented on src/Model/GameModel/Map/Generator/FileGenerating/FileGenerator.cpp
> +    std::string pathToMap = environmentVariablesProvider->getEnvironmentVariable(mapEnvVariableKey);
Обсудили, пофиксил с временным хардкодом имени файла для левела

2022-11-21 19:01 UTC, bagrorg requested changes

2022-11-21 19:01 UTC, bagrorg commented on src/Model/GameModel/Map/Generator/FileGenerating/FileGenerator.cpp
> +    std::vector<std::string> fileContent = fileReader.readFile(pathToMap + level1Map);
Вот тут опасно
Может случится так, что переменная выставлена как `/path/to/content` и тогда у нас получится `/path/to/contentmap.txt`
Добавь промежуточную `/`, а лучше всего воспользуйся `path` из `filesystem`
P.S. `/path/to/content//map.txt` является валидным путем

2022-11-21 19:01 UTC, bagrorg commented on src/Model/GameModel/Map/Generator/FileGenerating/FileGenerator.h
>          const std::string mapEnvVariableKey = "superrogue_map_path";
давай по брацки SUPERROGUE_CONTENT

2022-11-21 19:05 UTC, mandelshtamd commented on src/Model/GameModel/Map/Generator/FileGenerating/FileGenerator.h
>          const std::string mapEnvVariableKey = "superrogue_map_path";
ok

2022-11-21 19:06 UTC, mandelshtamd commented on src/Model/GameModel/Map/Generator/FileGenerating/FileGenerator.cpp
> +    std::vector<std::string> fileContent = fileReader.readFile(pathToMap + level1Map);
Добавил конкатенацию через "/", не хочу сейчас с filesystem разбираться(

2022-11-21 19:09 UTC, bagrorg approved these changes

2022-11-21 19:19 UTC, merged